### ISSUE TITLE
Any updates on when the dataset can be available? 

### ISSUE THREAD

**Issue by TamaraAtanasoska** [uclanlp/ParaAMR#1]
Just expressing interest. I would like to use the dataset in a research project I am doing. Thanks in advance for any release hints.

**Comment by Nicolas-BZRD** [comment]
Up

**Comment by richardbaihe** [comment]
up

**Comment by ej0cl6** [comment]
Thanks for your interest in our work and sorry for waiting. We now release the dataset and please see the details at https://github.com/amazon-science/ParaAMR
